# -*- coding: utf-8 -*-
"""

Automatically generated by Colab.

"""

from google.colab import drive
drive.mount('/content/drive')

!unzip /content/drive/MyDrive/indoor5.zip -d /content/Indoor5

!pip install ultralytics==8.3.20

from ultralytics import YOLO

model = YOLO("yolo11n.pt")


results = model.train(
    data="/content/Indoor5/data.yaml",
    epochs=50,
)

!cp -r /content/runs /content/drive/MyDrive/

!cp -r /content/runs /content/drive/MyDrive/

!cp -r /content/wandb /content/drive/MyDrive/